---
title: "Reproducible_Research_Proj1"
author: "JESTO"
date: "11/13/2020"
output: html_document
    keep_md: true
---

Loading ggplot2, dplyr package and data set.  Manipulating data to make it workable
====================================================================================

```{r, echo=TRUE}
library(ggplot2)
library(dplyr)
activity <- read.csv("./activity.csv", sep = ",", header = TRUE)
head(activity)
names(activity)
str(activity)
###Convert date format to date
activity$date <- as.POSIXct(activity$date, "%Y-%m-%d")
activity <- mutate(activity, weekday=weekdays(date))
head(activity)
names(activity)
str(activity)
summary(activity)
```

Total Steps Histogram total number of steps taken per day. Output mean, and median ?
===============================================================

```{r, echo=TRUE}
TotalStepsDay <- aggregate(steps ~ date, activity, FUN = sum, na.rm=TRUE)
head(TotalStepsDay)
##qplot(steps, data = TotalStepsDay, bins=15)
TotalStepsPlot <- ggplot(TotalStepsDay, aes(steps))
TotalStepsPlot + geom_histogram(bins=15, fill="red") + labs(title="Histogram Total Number of Steps per Day", x="Total Number of Steps", y="Frequency")

##Here is the mean of steps per day
mean(TotalStepsDay$steps, na.rm = TRUE)

##Here is the median of steps per day
median(TotalStepsDay$steps, na.rm = TRUE)

```



## What is mean total number of steps taken per day?



## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
